name:                cybus
version:             0.2.0.0
synopsis:            multi-dimensional arrays
description:
  A library for typesafe multi-dimensional arrays
  .
  Please see the README on GitHub at <https://github.com/gbwey/cybus#readme>
homepage:            https://github.com/gbwey/cybus#readme
license:             BSD3
author:              Grant Weyburne <gbwey9@gmail.com>
maintainer:          Grant Weyburne <gbwey9@gmail.com>
copyright:           2022 Grant Weyburne
category:            Data, Containers

github: gbwey/cybus.git

dependencies:
- base >= 4.7 && < 5
- adjunctions
- pos >= 0.2.0.0
- primus >= 0.2.0.0
- deepseq
- distributive
- indexed-traversable
- mtl
- profunctors
- semigroupoids
- transformers
- these
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  - -Wmonomorphism-restriction
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Widentities
  - -Wmissing-export-lists

tests:
  cybus-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    - -Wno-missing-export-lists
    - -Wno-missing-local-signatures
    dependencies:
    - base
    - cybus
    - lens
    - pretty-simple
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - checkers
    - QuickCheck

executables:
  cybus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    - -Wno-missing-local-signatures
    dependencies:
    - base
    - cybus
    # - lens
    # - pretty-simple

